#!/usr/bin/env bash

declare UPDATE_STYLE=none
declare DEFAULT_LEASE_TIME=600
declare MAX_LEASE_TIME=7200

declare DN_SERVERS

# This DHCP server also serves as the NAT server, so the
# IP address of LAN_IFACE will be the 'router' value.
declare LAN_IFACE




set_dn_servers()
{
    sed -E -n "s/^nameserver ([.[:digit:]]+)$/\1/p" /etc/resolv.conf
}


write_dhcpd()
{
    local target="${1:-&1}"

    echo -n > "$target"
    echo "ddns-update-style ${UPDATE_STYLE};"      >> "$target"
    echo "default-lease-time $DEFAULT_LEASE_TIME;" >> "$target"
    echo "max-lease-time $MAX_LEASE_TIME;"         >> "$target"
}



set_dn_servers
