#!/usr/bin/env bash

declare ROW_DELIM=$'\n'
declare FIELD_DELIM=$'|'

source bash_clargs

declare UPDATE_STYLE=none
declare DEFAULT_LEASE_TIME=600
declare MAX_LEASE_TIME=7200
declare WAN_IF
declare LAN_IF

declare -a DN_SERVERS

# This DHCP server also serves as the NAT server, so the
# IP address of LAN_IFACE will be the 'router' value.
declare LAN_IFACE

declare OIFS="$IFS"
IFS=$'\n'

declare -a CLOPTS=(
    "d|DEFAULT_LEASE_TIME|Default Lease Time"
    "u|UPDATE_STYLE|Update style"
    "m|MAX_LEASE_TIME|Max Lease Time"
    "w|WAN_IF|WAN Interface"
    "l|LAN_IF|LAN Interface"
    "h|->bash_clargs_usage|Show options and meanings"
    "s|->bash_clargs_show|Show current state of arguments."
)

IFS="$OIFS"




collect_dn_servers()
{
    local -n servers="DN_SERVERS"

    local IFS=$'\n'
    local -a nifaces
    nifaces=( $( ./ni_info -d ) )

    local niface
    local -a nirow
    local ipaddr

    for niface in "${nifaces[@]}"; do
        IFS=' '
        nirow=( $niface )
        if [ "${#nirow[@]}" -gt 1 ]; then
            for ipaddr in "${nirow[@]:1}"; do
                servers+=( $ipaddr )
            done
        fi
    done
}

show_dn_servers()
{
    echo "There are ${#DN_SERVERS[@]} dns entries." >&2
    echo "They are:" >&2

    local server
    for server in "${DN_SERVERS[@]}"; do
        echo "$server" >&2
    done
}

make_dns_option_line()
{
    echo -n "option domain-name-servers "

    local ns
    local -i add_comma=0
    for ns in "${DN_SERVERS[@]}"; do
        if [ "$add_comma" -eq 0 ]; then
            add_comma=1
        else
            echo -n ", "
        fi
        echo -n "$ns"
    done
    echo ";"
}


write_dhcpd()
{
    local target="${1:-/dev/stdout}"

    echo -n > $target

    make_dns_option_line                           >> $target


    echo "ddns-update-style ${UPDATE_STYLE};"      >> $target
    echo "default-lease-time $DEFAULT_LEASE_TIME;" >> $target
    echo "max-lease-time $MAX_LEASE_TIME;"         >> $target

    echo "authoritative;"                          >> $target
}


bash_clargs_process "$@"

collect_dn_servers

write_dhcpd

