#!/usr/bin/env bash

# For commandline processing

declare -a CLOPTS=(
    "h|->bash_clargs_usage|Show help"
    "e|IF_EXT|Set external interface name"
    "i|IF_INT|Set internal interface name"
    "n|INT_NET|Set internal internet base address"
    "s|-SKIP_INTERACTIVE|Skip setting parameters interactively."
    "w|-WRITE_CONFIGS|Write configuration files.  Must be root."
)

source bash_clargs


# This script file collects network information
source nif_info

declare IF_EXT=$( nif_find_external_name )
declare IF_INT=$( nif_find_first_internal_name )
declare IP_INT=$( nif_find_first_internal_addr )
declare INT_NET=$( nif_network_source_address "$IP_INT" )
declare -i SKIP_INTERACTIVE=0
declare -i WRITE_CONFIGS=0

clear_screen() { echo -n "[2J"; }
is_root() { [ "$USER" = "root" ]; }
is_write_mode() { [ "$WRITE_CONFIGS" -eq 1 ]; }

already_installed()
{
    local pname="$1"
    local gresult
    gresult=$( dpkg -s "${pname}" 2>/dev/null | grep ^Status )
    # falling out of function will allow calling function to
    # query the result of the `which` command.
}

get_keypress()
{
    local prompt="${1:=Press any key}"

    local IFS=''

    # Array to collect chars in case of multi-char keypress
    local -a chars=( )
    
    # Wait for a keypress (-n 1), save to array
    local keychar
    read -n 1 -s -p "${prompt}" keychar
    chars=( "$keychar" )

    # Collect additional characters if available, especially for escape characters
    while read -t 0; do
        read -n 1 keychar
        chars=( "${chars[@]}" "$keychar" )
    done

    # empty IFS so array is joined without delimiters
    echo "${chars[*]}"
}

validate_ip4()
{
    local IFS=$'.'
    local -a parts=( $1 )
    local part
    local -i pval
    if [ "${#parts[@]}" -eq 4 ]; then
        for part in "${parts[@]}"; do
            echo "part is '[32;1m${part}[m'"
            if [[ "${part}" =~ [0-9]+ ]]; then
                pval="$part"
                if [ "$pval" -gt 255 ]; then
                   echo "The value, '$part', is out of range." >&2
                   read -n1
                   return 1
                fi
            else
                echo "The value, '$part' is not a number." >&2
                read -n1
                return 1
            fi
        done
        
    else
        echo "Invalid IP address, it has ${#parts[@]} parts, it should have 4." >&2
        read -n1
        return 1
    fi

    return 0

}

get_int_net()
{
    local -n ip4val="$1"
    local prompt
    if [ "${#ip4val}" -gt 6 ]; then
        prompt="Currently ${ip4val}, enter"
    else
        prompt="Enter"
    fi

    local newip4
    while [ 1 -eq 1 ]; do
        clear_screen
        echo "Enter the network source IP address."
        echo
        read -p "$prompt an IP address, or 'q' to quit: " newip4
        if [ "$?" -eq 0 ]; then
            if [ "$newip4" = 'q' ]; then
                return 1;
            elif validate_ip4 "$newip4"; then
                ip4val="$newip4"
                return 0
            else
                echo "Invalid ip address."
            fi
        else
            echo "Read returned a non-zero exit value."
            break
        fi
    done

    read -n1
    return 1
}

get_iface_name_index()
{
    local curname="$1"

    local -i index=0
    local name

    local iface
    for iface in "${IFACES[@]}"; do
        name=$( nif_get_name "${IFACES[$index]}" )
        if [ "$curname" = "$name" ]; then
            echo "$index"
            return 0
        fi
        (( ++index ))
    done
    return 1
}

show_interface_choices()
{
    local curchoice=$( nif_get_name "$1" )
    local direction="$2"
    local namecol="[1;4m"
    local defcol="[m"
    local curcol

    local iface
    local name
    local addr
    local index=1

    clear_screen
    echo "curchoice is [33;1m$curchoice[m and direction is [33;1m$direction[m"
    echo "Select a device for the [36;1m$direction[m interface."
    echo "The ${namecol}current selection${defcol} is highlighted."
    echo

    for iface in "${IFACES[@]}"; do
        name=$( nif_get_name "$iface" )
        addr=$( nif_get_addr "$iface" )
        if [ $? -ne 0 ]; then
            addr="NA"
        fi

        echo -n "name is [33;1m$name[m  "

        if [ "$name" = "$curchoice" ]; then
            curcol="$namecol"
        else
            curcol="$defcol"
        fi

        echo "$index. ${curcol}$name${defcol} ($addr)"
        (( ++index ))
    done

}

select_interface()
{
    local -n ret_val="$1"
    ret_val=

    local name_iface="$2"
    local type_iface="$3"
    local resp
    local -i max_index="${#IFACES[@]}"
    local -i cur_index=$( get_iface_name_index "$name_iface" )
    local -i sel_index

    while true; do
        show_interface_choices "$name_iface" "$type_iface"
        echo "q. to keep current choice"
        echo
        read -n 1 -p "Select an interface: " resp
        echo

        case "$resp" in
            [1-9] )
                sel_index=$(( $resp - 1 ))
                if [ "$sel_index" -lt "$max_index" ]; then
                    ret_val=$( nif_get_name "${IFACES[$sel_index]}" )
                    return 0
                fi
                ;;
            q ) break ;;
        esac
    done

    return 1
}

show_network_defaults()
{
    clear_screen
    echo "1. IF_EXT is [33;1m$IF_EXT[m"
    echo "2. IF_INT is [33;1m$IF_INT[m"
    echo "3. INT_NET is [33;1m$INT_NET[m"
}

make_date_suffix() { date +%Y%m%d.%H%M%S; }

backup_script()
{
    local target="$1"
    if [ -f "$target" ]; then
        local new_target="$target.$( make_date_suffix )"
        echo "Saving [32;1m$target[m to [32;1m$new_target[m"
        # mv "$target" "$new_target"
    fi
}

generate_dhcpd()
{
    local -a args=(
        -a "$INT_NET"
        -i "$IF_INT"
        -e "$IF_EXT"
    )

    local target="$1"

    if is_write_mode; then
        backup_script "$target"
        ./build_dhcpd_conf "${args[@]}" > "$target"
    else
        echo
        echo "[33;1m$target[m:"
        ./build_dhcpd_conf
        echo
    fi
}

prepare_iptables()
{
    local -a args=(
        -a "$INT_NET"
        -i "$IF_INT"
        -e "$IF_EXT"
        -s
    )

    ./new_iptables "${args[@]}"
}

update_default_isc_dhcp_server()
{
    local iface="$IF_INT"

    local -a sargs=(
        -e 's/\(INTERFACESv4=\"\).*/\1'"$1"'\"/'
        -e 's/#\(DHCPDv4.*\)/\1/'
    )

    sed -i "${sargs[@]}" /etc/default/isc-dhcp-server
    if [ $? -eq 0 ]; then
        echo "Success updating [32;1m/etc/default/isc-dhcp-server[m"
    else
        echo "[31;1mFAILED[m updating [31;1m/etc/default/isc-dhcp-server[m"
    fi
}

confirm_network_defaults()
{
    local -n if_ext="IF_EXT"
    local -n if_int="IF_INT"
    local -n int_net="INT_NET"
    local resp
    local new_iface
    local new_address
    while true; do
        show_network_defaults
        echo "a. to accept defaults"
        echo "q. to quit"
        echo 
        read -n 1 -p "Type a number " resp
        echo
        case "$resp" in
            1 )
                if select_interface new_iface "$if_ext" "external"; then
                    if_ext="$new_iface"
                fi ;;
            2 )
                if select_interface new_iface "$if_int" "internal"; then
                    if_int="$new_iface"
                fi ;;
            3 ) get_int_net "int_net" ;;
            a ) break ;;
            q ) exit 0 ;;
            * ) echo "Unknown entry.  Try again." ;;
        esac
    done
}


bash_clargs_process "$@"

echo "INT_NET has ${#INT_NET} characters"

bash_clargs_show

if [ "${SKIP_INTERACTIVE}" -eq 0 ]; then
    confirm_network_defaults
fi

if is_write_mode; then
    if is_root; then
        if [ "${#INT_NET}" -lt 8 ]; then
            echo "Missing valid internal network address."
            exit 1
        fi

        hl_install isc-dhcp-server

        echo "About to write dhcp server configuration files."
        generate_dhcpd "/etc/dhcp/dhcpd.conf"
        update_default_isc_dhcp_server

        echo "Starting isc-dhcp-server"
        service isc-dhcp-server restart

        prepare_iptables
    else
        echo "Must be root to write scripts."
    fi
else
    generate_dhcpd "/etc/dhcp/dhcpd.conf"
fi

