#!/usr/bin/env bash

declare SOURCE="${1:-/var/log/syslog}"

declare FIELD_DELIM=$'\t'

declare -A FIELDS=()
declare -a FIELDNAMES=()
declare -a LINES=()

clear_screen() { echo -n "[2J"; }
top_screen()   { echo -n "[1;1H"; }

# Waits for and returns single keypress, even if it is
# represented by multiple characters.
get_keypress()
{
    # IFS characters will be invisible to 'read', so:
    local IFS=''

    local prompt="${1:=Press any key}"

    # Array to collect chars in case of multi-char keypress
    local -a chars=( )
    
    # Wait for a keypress (-n 1), save to array
    local keychar
    read -n 1 -s -r -p "${prompt}" keychar
    chars=( "$keychar" )

    # Collect additional characters if available, especially for escape characters
    while read -t 0; do
        read -n 1 keychar
        chars=( "${chars[@]}" "$keychar" )
    done

    # empty IFS so array is joined without delimiters
    echo "${chars[*]}"
}

# Enter escape character in EMACS with C-q, ESC
# (see documentation: info emacs -n "Inserting Text")
declare keypress_down_arrow='[B'
declare keypress_up_arrow='[A'


# Simple boolean function that names its test
field_added() { [ -v FIELDS[$1] ]; }

# Returns the field index through echo.  Does not disturb
# the global FIELDS array.
field_index()
{
    if field_added "$1"; then
        echo "${FIELDS[$1]}"
        return 0
    else
        return 1
    fi
}

# Like field_index(), returns the index if the name is found,
# but it adds the name to the collection if it is not already
# included in the array.
#
# Because this function modifies global variables, it must
# not be called in a subprocess, that is, within $( ... )
# operators.  The index value is returned to an indirect variable
# that the calling function identifies in its parameter list.
prepare_field_index()
{
    local -n retval="$1"
    local name="$2"
    if field_added $name; then
        retval="${FIELDS[$name]}"
    else
        retval="${#FIELDS[@]}"
        FIELDS["$name"]="$retval"
        FIELDNAMES=( "${FIELDNAMES[@]}" "$name" )
    fi
}

# Boolean function that indicates if a given "needle"
# value ($2) is found in the "haystack" ($1).
element_included()
{
    local -n haystack="$1"
    local needle="$2"
    local value
    for value in "${haystack[@]}"; do
        if [ "$value" = "$needle" ]; then
            return 0
        fi
    done
    return 1
}

# Supports read_syslog(), breaking a line into an array
# of values, updating the FIELDS and FIELDNAMES arrays
# as unknown columns are encountered.
process_syslog_line()
{
    local IFS=$' '
    local -a rawline=( $1 )
    local -n Lines=LINES
    local -a line=()

    local elem name value index
    local -a pair
    IFS=$'='
    for elem in "${rawline[@]}"; do
        if [[ "$elem" =~ ([^=]+)=([^[:space:]]+) ]]; then
            pair=( $elem )
            name="${pair[0]}"
            value="${pair[1]}"
            prepare_field_index index $name
            line[$index]="$value"
        fi
    done

    IFS="$FIELD_DELIM"
    Lines=("${Lines[@]}" "${line[*]}" )
}

# Fill global variables with the contents of /var/log/syslog
read_syslog()
{
    local line
    local -i count=0

    clear_screen

    while read -r line; do
        top_screen
        echo "Reading syslog line $count"
        if [[ "$line" =~ \.*IPT\.* ]]; then
            process_syslog_line "$line"
            (( ++count ))
        fi
    done < "$SOURCE"
}

# Make array of indicies matching the submitted field names
# @param $1 (target) is the array in which the result is returned.
# @param $2 (source) is an array of field names to be processed.
# 
# target will contain the field indexes into the array that is
# resolved from lines in the LINES array.
make_field_indicies_array()
{
    local -n target="$1"
    local -n source="$2"

    target=()

    local field
    for field in "${source[@]}"; do
        field="${field^^}"
        if [ -v FIELDS[$field] ]; then
            target=( "${target[@]}" "${FIELDS[$field]}" )
        else
            echo "Field $field was not found." >&2
        fi
    done
}

# Get max length for each requested column
# @param $1 (target) is the array in which the result is returned.
# @param $2 (source) is an array of column indices whose max length
#           is to be calculated.  This is array is the result of the
#           make_field_indicies_array() function.
# @param $3 is the additional spaces to add to each max value
#           to separate the columns.
make_field_widths_array()
{
    local -n target="$1"
    local -n source="$2"
    local -i margin="${3:0}"

    # Initialize the array with the length of the FIELD name,
    # which will head each column:
    target=()
    local -i icount="${#source[*]}"
    local -i ndx
    local name
    for (( ndx=0; ndx<icount; ++ndx )); do
        target[$ndx]="${#FIELDNAMES[${source[$ndx]}]}"
    done

    local line
    local -a lparts
    local IFS="$FIELD_DELIM"
    local -i curlen

    for line in "${LINES[@]}"; do
        lparts=( $line )
        for (( ndx=0; ndx<icount; ++ndx )); do
            curlen="${#lparts[${source[$ndx]}]}"
            if [ "$curlen" -gt "${target[$ndx]}" ]; then
                target[$ndx]="$curlen"
            fi
        done
    done

    if [ "$margin" -gt 0 ]; then
        for (( ndx=0; ndx<icount; ++ndx )); do
            target[$ndx]=$(( target[$ndx] + $margin ))
        done
    fi
}

# Supports select_fields() through display_selection_fields()
get_max_field_name_length()
{
    local name
    local -i maxlen=0
    for name in "${FIELDNAMES[@]}"; do
        if [ "${#name}" -gt "$maxlen" ]; then
            maxlen="${#name}"
        fi
    done

    echo "$maxlen"
}

# Supports select_fields(), this function refreshes the display
# of field names and their status (included in report or not).
display_selection_fields()
{
    local -n sellist="$1"
    local -n hilite="$2"

    local fname
    local -i ndx
    local -i maxfnamelen=$( get_max_field_name_length )

    local IFS="$FIELD_DELIM"
    local -a sampleline=( ${LINES[0]} )
    local sample

    local -i curline=0
    for fname in "${FIELDNAMES[@]}"; do
        if [ "$(( curline++ ))" -eq "$hilite" ]; then
            echo -n "[44m"
        fi

        ndx="${FIELDS[$fname]}"
        sample="${sampleline[${FIELDS[$fname]}]}"

        if element_included sellist "$fname"; then
            echo -n "|X| "
        else
            echo -n "| | "
        fi
        printf "%-${maxfnamelen}s [37;2m e.g. %s[m" "$fname" "$sample"
        echo
    done
}

# Supports select_fields(), this function manipulates a
# space-separated list of field names according to the
# indicated name.  Adds to the list if not already included,
# or removed from list if it's in the list.
toggle_field()
{
    local -n target="$1"
    local tname="$2"
    local name
    local -i index=0
    local -i index_limit="${#target[@]}"

    # Simple process for an empty array
    if [ "$index_limit" -eq 0 ]; then
        echo "$tname"
        return 0
    fi

    for name in "${target[@]}"; do
        # Found? remove it
        if [ "$name" = "$tname" ]; then
            if [ "$index" -eq 0 ]; then
                echo "${target[*]:1}"
                return 0
            else
                echo "${target[*]:0:$index} ${target[$(( index+1 ))]}"
                return 0
            fi
        fi

        (( ++index ))
    done

    # Not found? add to end:
    echo "${target[*]} $tname"
    return 0
}

# "Dialog" that shows the collection of field names, from
# which the user will select names.
#
# The result of the users' selections will be placed in the
# indirect array variable initialized with $1.
select_fields()
{
    local -n target="$1"
    local -a tmirror=( "${target[@]}" )

    local -i active_line=0
    local -i line_limit="${#FIELDNAMES[@]}"

    local prompt="UP or DOWN arrows to move, SPACE to toggle, ENTER to accept, q to abort"
    local keystroke

    while true; do
        clear_screen
        top_screen
        display_selection_fields tmirror active_line

        keystroke=$( get_keypress "$prompt" )

        if [ "${#keystroke}" -eq 0 ]; then
            target=( "${tmirror[@]}" )
            return 0
        fi
            
        case "$keystroke" in
            "$keypress_down_arrow" ) (( ++active_line )) ;;
            "$keypress_up_arrow" ) (( --active_line )) ;;

            ' ') tmirror=( $( toggle_field tmirror "${FIELDNAMES[$active_line]}" ) ) ;;
            q ) return 1 ;;
            *)
                if [ "${keystroke:0:1}" = "" ]; then
                    keystroke="^[${keystroke:1}"
                fi
                echo "keystroke is [32m${keystroke}[m" ;;
        esac

        if [ "$active_line" -lt 0 ]; then
            active_line=0
        elif [ "$active_line" -ge "$line_limit" ]; then
            active_line=$(( line_limit-1 ))
        fi
    done
}

# Display the requested columns from the global LINES array
# collected from the syslog file.
show_lines()
{
    local -a fields=( "$@" )
    if [ "${#fields[@]}" -eq 0 ]; then
        fields=( ${!FIELDS[@]} )
    fi
    
    local -a indicies widths
    make_field_indicies_array indicies fields
    make_field_widths_array widths indicies 2

    local IFS="$FIELD_DELIM"
    local line value
    local -a lparts
    local -i ndx
    local -i colw valw
    local -i curcol

    # Write a highlighted headers line
    echo -n "[32;1m"
    curcol=0
    for ndx in "${indicies[@]}"; do
        colw="${widths[$(( curcol++ ))]}"
        format="%-${colw}s"
        printf "$format" "${FIELDNAMES[$ndx]}"
    done
    echo "[m"

    # Write table details
    for line in "${LINES[@]}"; do
        lparts=( $line )
        curcol=0
        for ndx in "${indicies[@]}"; do
            colw="${widths[$(( curcol++ ))]}"
            format="%-${colw}s"
            printf "$format" "${lparts[$ndx]}"
        done
        echo
    done
}


main()
{
    read_syslog

    local -a flist=()

    if select_fields flist; then
        clear_screen
        top_screen

        show_lines "${flist[@]}"
    fi
}


main
echo
